# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1a34c39bea0b7837fc0821b8d1f714c7abf8e9ae7907904d9c6760db7f2dd8a332a129b3997d8ad05c4d704c9002f89b93bca17a74d0cc95c2881a33099dc76

test:
  secret_key_base: bc2a2a3e8192bcaf62019e7eb7b5df4e891b3204d8050951944c7d020dc6cdf6b118aefa11fecd943a8f504eea6c13da578b6806c3d9e2f2057e2eda30685f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
